import {test,expect} from '@playwright/test';
import {engineExecutable} from '../analysis-service.mjs';
import {createServer} from 'node:http';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const dir=process.env.EPLYX_REPORT_DIR||'reports/milestone4-validation';
const digest=b=>createHash('sha256').update(b).digest('hex');
const source='741ZXYKzgjPZucRhPUQFK7kKAgP1ESJwimhumgGpuPHs';
const owner='2wCvQzHiDHAHTvzwPeof9H3uEzq8Bzvg38DFbvZMGkuj';
async function wallet(page){const response=page.waitForResponse(r=>r.url().endsWith('/api/runs')&&r.request().method()==='POST');await page.locator('#run-analysis').click();const queued=await response;expect(queued.status()).toBe(202);const job=await queued.json();await expect(page.locator(`.wallet-output[data-run="${job.id}"]`)).toBeVisible({timeout:100000});return (await page.request.get(new URL(`/api/runs/${job.id}`,page.url()).href)).json();}
async function transfer(page,parent,recipient,label,focusedSource=source){await page.locator(`[name="focused_account"][value="${focusedSource}"]`).check();await expect(page.locator('.local-checks')).toContainText('Not tested yet for this run');await page.locator('[name="recipient"]').fill(recipient);const accepted=page.waitForResponse(r=>r.url().endsWith(`/api/runs/${parent.id}/checks`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Run local check',exact:true}).click();const response=await accepted;expect(response.status()).toBe(202);let job=await response.json();await expect.poll(async()=>{job=await(await page.request.get(new URL(`/api/runs/${job.id}`,page.url()).href)).json();return job.status;},{timeout:150000}).toBe('Completed');await expect(page.locator(`[data-check="${job.id}"]`)).toContainText('Passed in local simulation',{timeout:15000});expect(job.result.status).toBe('Proven');expect(job.result.execution_performed).toBe(true);expect(job.result.execution.compute_units).toBeGreaterThan(0);expect(job.result.signer_possession_known).toBe(false);expect(job.result.reconciliation.reconciled).toBe(true);expect(job.result.readiness).toBeNull();
 const capture=await(await page.request.get(new URL(`/api/runs/${job.id}/capture`,page.url()).href)).body();expect(digest(capture)).toBe(job.capture_sha256);const input=`${dir}/${label}.capture.json`;await writeFile(input,capture);const replay=execFileSync(engineExecutable,['replay-current-check','--input',input,'--run-id',parent.id,'--check-id',job.id,'--wallet-sha256',parent.capture_sha256,'--capture-sha256',job.capture_sha256],{env:{PATH:process.env.PATH},maxBuffer:32*1024*1024});expect(digest(replay)).toBe(job.canonical_sha256);await writeFile(`${dir}/${label}.result.json`,replay);await writeFile(`${dir}/${label}.job.json`,JSON.stringify(job,null,2));return job;}
async function workflow(page,base,recipient,prefix){
 await mkdir(dir,{recursive:true});await page.goto(`${base}/analysis#analysis`);await expect(page.locator('[name="asset"] option')).toHaveCount(9);const catalogue=await(await page.request.get(`${base}/api/catalogue`)).json();const asset=catalogue.entries.find(e=>e.assertions[0].symbol==='SPACEX');await page.locator('[name="scope"]').selectOption('wallet');await page.locator('[name="asset"]').selectOption(asset.mint);await page.locator('[name="public_owner"]').fill(owner);
 const parent=await wallet(page);expect(parent.result.paths.every(p=>p.status==='NotTested')).toBe(true);expect(parent.result.wallet_observation.token_accounts.some(a=>a.address===source)).toBe(true);const first=await transfer(page,parent,recipient,`${prefix}-transfer`);
 await page.getByRole('button',{name:'Technical',exact:true}).click();await expect(page.locator(`[data-check="${first.id}"]`)).toContainText('Passed in local simulation');await page.getByRole('button',{name:'Overview',exact:true}).click();await page.reload();await expect(page.locator(`[data-check="${first.id}"]`)).toContainText('Passed in local simulation');
 await page.locator('.local-checks').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/${prefix}-transfer-desktop.png`});await page.setViewportSize({width:390,height:844});await page.locator('.local-checks').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/${prefix}-transfer-mobile.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 const refreshed=await wallet(page);expect(refreshed.id).not.toBe(parent.id);expect(refreshed.result.paths.every(p=>p.status==='NotTested')).toBe(true);await expect(page.locator('.execution-result')).toHaveCount(0);const second=await transfer(page,refreshed,recipient,`${prefix}-refresh-transfer`);expect(second.capture_sha256).not.toBe(first.capture_sha256);expect(second.id).not.toBe(first.id);
 for(const [name,job] of [['wallet',parent],['refresh-wallet',refreshed]]) {const bytes=await(await page.request.get(`${base}/api/runs/${job.id}/capture`)).body();await writeFile(`${dir}/${prefix}-${name}.capture.json`,bytes);await writeFile(`${dir}/${prefix}-${name}.job.json`,JSON.stringify(job,null,2));}
 if(prefix==='fixture') {
  await page.locator('.local-check-form [name="path"]').selectOption('SecondaryMarketExit');await page.locator('[name="minimum_output_decimal"]').fill('1000000');
  const response=page.waitForResponse(r=>r.url().endsWith(`/api/runs/${refreshed.id}/checks`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Discover & test',exact:true}).click();expect((await response).status()).toBe(202);const market=await(await response).json();
  await expect(page.locator(`[data-check="${market.id}"]`)).toContainText('This exact tested route failed in local simulation',{timeout:60000});await expect(page.locator('.wallet-output')).toHaveAttribute('data-run',refreshed.id);await expect(page.locator(`[data-check="${second.id}"]`)).toContainText('Passed in local simulation');
  const outcome=await(await page.request.get(`${base}/api/runs/${market.id}`)).json();expect(outcome.result.execution_performed).toBe(true);expect(outcome.result.reconciliation.reconciled).toBe(true);expect(outcome.result.reconciliation.input_debited_raw).toBe('0');expect(outcome.result.discovery.global_exitability_established).toBe(false);
  await writeFile(`${dir}/fixture-market-failure.job.json`,JSON.stringify(outcome,null,2));await page.locator(`[data-check="${market.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/fixture-market-failure.png`});
 }
 const invalid=await page.request.post(`${base}/api/runs/${refreshed.id}/checks`,{data:{request_key:crypto.randomUUID(),request:{...second.check_request,program_id:'arbitrary'}}});expect(invalid.status()).toBe(400);await expect(page.locator('.wallet-output')).toBeVisible();
}
test('current transfer browser/service/engine and offline VM replay using deterministic reconstructed RPC',async({page})=>{
 test.setTimeout(240000);const revive=(_key,value,context)=>typeof value==='number'&&!Number.isSafeInteger(value)?JSON.rawJSON(context.source):value;const fixture=JSON.parse(await readFile('probes/phase7-captures/fixtures/group-0.json','utf8'),revive),marketFixture=JSON.parse(await readFile('probes/phase7-captures/fixtures/group-1.json','utf8'),revive),batch=fixture.evidence[3],raw=new Map(batch.params[0].map((a,i)=>[a,batch.result.value[i]])),slot=marketFixture.evidence[3].result.context.slot;for(const [i,a] of marketFixture.evidence[3].params[0].entries())raw.set(a,marketFixture.evidence[3].result.value[i]);
 const rpc=createServer(async(req,res)=>{let body='';for await(const b of req)body+=b;const {method,params}=JSON.parse(body);let result;if(method==='getGenesisHash')result=fixture.evidence[0].result;else{let value;if(method==='getAccountInfo')value=raw.get(params[0])??null;else if(method==='getMultipleAccounts')value=params[0].map(a=>raw.get(a)??null);else if(method==='getProgramAccounts')value=[...raw.entries()].filter(([,v])=>v?.owner==='LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo'&&v?.space===904).map(([pubkey,account])=>({pubkey,account}));else if(method==='getTokenAccountsByOwner')value=[{pubkey:source,account:raw.get(source)}];else throw new Error(method);result={context:{slot},value};}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:1,result}));});rpc.listen(0,'127.0.0.1');await once(rpc,'listening');const port=4198,base=`http://127.0.0.1:${port}`,service=spawn(process.execPath,['frontend/serve.mjs'],{env:{...process.env,PORT:String(port),SOLANA_RPC_URL:`http://127.0.0.1:${rpc.address().port}/secret-test-key`},stdio:'pipe'});
 try{await expect.poll(async()=>{try{return(await fetch(`${base}/api/health`)).status;}catch{return 0;}}).toBe(200);await workflow(page,base,'124XHuTYUNnCf2ABCNcCEdQFpHQ7Y6MnPe9NeouDB1az','fixture');}finally{service.kill();rpc.close();await once(service,'exit');}
});
test('live current transfer and refreshed transfer with exact offline VM replay',async({page,baseURL})=>{
 test.skip(process.env.EPLYX_EXECUTION_LIVE!=='1','Opt-in bounded read-only live execution-state capture');test.setTimeout(360000);expect(process.env.EPLYX_TRANSFER_RECIPIENT,'Explicit public recipient token account required').toBeTruthy();await workflow(page,baseURL,process.env.EPLYX_TRANSFER_RECIPIENT,'live');
});

test('live bounded current market discovery and exact offline replay',async({page,baseURL})=>{
 test.skip(process.env.EPLYX_MARKET_LIVE!=='1','Opt-in bounded current DLMM acceptance');test.setTimeout(240000);await mkdir(dir,{recursive:true});
 await page.goto(`${baseURL}/analysis#analysis`);await expect(page.locator('[name="asset"] option')).toHaveCount(9);const catalogue=await(await page.request.get(`${baseURL}/api/catalogue`)).json();await page.locator('[name="scope"]').selectOption('wallet');await page.locator('[name="asset"]').selectOption(catalogue.entries.find(e=>e.assertions[0].symbol==='SPACEX').mint);await page.locator('[name="public_owner"]').fill(owner);const parent=await wallet(page);await page.locator(`[name="focused_account"][value="${source}"]`).check();await page.locator('.local-check-form [name="path"]').selectOption('SecondaryMarketExit');await page.locator('[name="minimum_output_decimal"]').fill('0.0001');
 const accepted=page.waitForResponse(r=>r.url().endsWith(`/api/runs/${parent.id}/checks`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Discover & test',exact:true}).click();expect((await accepted).status()).toBe(202);let job=await(await accepted).json();await expect.poll(async()=>{job=await(await page.request.get(`${baseURL}/api/runs/${job.id}`)).json();return job.status;},{timeout:150000}).toBe('Completed');expect(['Proven','Failed','Indeterminate','Unsupported']).toContain(job.result.status);await expect(page.locator(`[data-check="${job.id}"]`)).toBeVisible();
 const capture=await(await page.request.get(`${baseURL}/api/runs/${job.id}/capture`)).body();await writeFile(`${dir}/live-market.capture.json`,capture);const replay=execFileSync(engineExecutable,['replay-current-check','--input',`${dir}/live-market.capture.json`,'--run-id',parent.id,'--check-id',job.id,'--wallet-sha256',parent.capture_sha256,'--capture-sha256',job.capture_sha256],{env:{PATH:process.env.PATH},maxBuffer:32*1024*1024});expect(digest(replay)).toBe(job.canonical_sha256);await writeFile(`${dir}/live-market.result.json`,replay);await writeFile(`${dir}/live-market.job.json`,JSON.stringify(job,null,2));await writeFile(`${dir}/live-market-wallet.job.json`,JSON.stringify(parent,null,2));await page.locator('.execution-result').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/live-market-desktop.png`});
 expect(job.result.signer_possession_known).toBe(false);expect(job.result.readiness).toBeNull();if(job.result.execution_performed){expect(job.result.execution.compute_units).toBeGreaterThan(0);expect(job.result.discovery.global_exitability_established).toBe(false);}await expect(page.locator('.wallet-output')).toBeVisible();
});


test('live second catalogue asset transfers freshly captured OPENAI holdings',async({page,baseURL})=>{
 test.skip(process.env.EPLYX_SECOND_EXECUTION_LIVE!=='1','Opt-in bounded second-asset transfer acceptance');test.setTimeout(180000);await mkdir(dir,{recursive:true});
 const secondOwner='6GJbPKBtovsrMEEMcic5KMi5tswh9qSyT5ZYLMqEwNgt',secondSource='F3L4drnkirxAnqeFVpJiRgTUeNMdBFZnV4bwZKuyrSpy',recipient='Ft3bKc8RLPz8NaXEwUdttnG1PgKiN8q3ULMX5pmQ1WeZ';
 await page.goto(`${baseURL}/analysis#analysis`);await expect(page.locator('[name="asset"] option')).toHaveCount(9);const cat=await(await page.request.get(`${baseURL}/api/catalogue`)).json();const asset=cat.entries.find(e=>e.assertions[0].symbol==='OPENAI');await page.locator('[name="scope"]').selectOption('wallet');await page.locator('[name="asset"]').selectOption(asset.mint);await page.locator('[name="public_owner"]').fill(secondOwner);
 const parent=await wallet(page);expect(parent.result.wallet_observation.token_accounts.some(a=>a.address===secondSource)).toBe(true);const checked=await transfer(page,parent,recipient,'live-second-transfer',secondSource);expect(checked.result.mint).toBe(asset.mint);expect(checked.result.source).toBe(secondSource);expect(checked.result.owner).toBe(secondOwner);
 await writeFile(`${dir}/live-second-wallet.job.json`,JSON.stringify(parent,null,2));await writeFile(`${dir}/live-second-wallet.capture.json`,await(await page.request.get(`${baseURL}/api/runs/${parent.id}/capture`)).body());await page.locator('.execution-result').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/live-second-transfer-desktop.png`});
});
