import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash,randomUUID} from 'node:crypto';
import {AnalysisService} from '../analysis-service.mjs';
import {validatePreflightFields} from '../preflight-service.mjs';
const root=resolve('.'),hash=b=>createHash('sha256').update(b).digest('hex');
const request=()=>({source:'741ZXYKzgjPZucRhPUQFK7kKAgP1ESJwimhumgGpuPHs',successor_mint:null,effective_at:'2035-01-01T00:00:00Z',deadline:null,post_deadline:null,assurance:'FullTransition',check_ids:[]});
async function setup(){const directory=await mkdtemp(resolve(tmpdir(),'eplyx-preflight-'));const service=new AnalysisService({root,directory});await service.initialize();const old=JSON.parse(await readFile('reports/milestone4-validation/live-transfer.capture.json'));const capture=old.wallet_capture,id=randomUUID();const c=JSON.parse(capture);const parent={id,owner:'session-a',status:'Completed',selection:{asset:'mint',review:'current',stage:null,check:null,cluster:'solana-mainnet',mint:c.asset.mint,catalogue_version:null,sample_accounts:false,scope:'wallet',public_owner:c.selection.public_owner},capture_sha256:hash(capture)};service.jobs.set(id,parent);await writeFile(resolve(directory,`${id}.capture.json`),capture);return {directory,service,parent};}
async function finish(service){for(let i=0;i<200&&service.running;i++)await new Promise(r=>setTimeout(r,50));assert.equal(service.running,false);}
test('prospective structured fields reject proof, programs, paths and unsupported semantics',()=>{
 assert.deepEqual(validatePreflightFields(request()),request());
 for(const field of ['status','rpc','input','program','scenario','source_kind','policy','engine'])assert.throws(()=>validatePreflightFields({...request(),[field]:'injected'}));
 for(const patch of [{post_deadline:'NoIssuerEntitlement'},{assurance:'Population'},{check_ids:['saved-phase7']},{successor_mint:{}},{effective_at:1}])assert.throws(()=>validatePreflightFields({...request(),...patch}));
});
test('real offline preflight persists bound scenario and survives restart with zero acquisition',async()=>{
 const {directory,service,parent}=await setup();try{let network=false;const runner=service.runner;service.runner=(exe,args,options)=>{network ||= !!options.fresh;return runner(exe,args,options);};const key=randomUUID();const job=await service.submitPreflight(parent.id,request(),key,'session-a');await finish(service);assert.equal(job.status,'Completed');assert.equal(network,false);assert.equal(job.result.proposed_change.source,'UserProposed');assert.equal(job.result.views[1].readiness.full_transition.status,'Incomplete');assert.equal(job.result.population_readiness,null);assert.equal((await service.submitPreflight(parent.id,request(),key,'session-a')).id,job.id);const restarted=new AnalysisService({root,directory});await restarted.initialize();assert.equal(restarted.get(job.id).canonical_sha256,job.canonical_sha256);assert.equal(hash(await restarted.artifact(job.id)),job.canonical_sha256);assert.equal(hash(await restarted.artifact(job.id,true)),job.capture_sha256);assert.equal(JSON.parse(await readFile(resolve(directory,`${job.id}.scenario.json`))).created_for_run,parent.id);await writeFile(resolve(directory,`${job.id}.capture.json`),'tampered');await assert.rejects(()=>service.artifact(job.id,true),/EvidenceVerificationFailed/);}finally{await rm(directory,{recursive:true,force:true});}
});
test('preflight rejects cross-session, refresh, focus and invalid time before acquisition',async()=>{
 const {directory,service,parent}=await setup();try{await assert.rejects(()=>service.submitPreflight(parent.id,request(),randomUUID(),'other-session'),/InvalidParent/);await assert.rejects(()=>service.submitPreflight(parent.id,{...request(),effective_at:'2020-01-01T00:00:00Z'},randomUUID(),'session-a'),/InvalidPreflight/);await assert.rejects(()=>service.submitPreflight(parent.id,{...request(),source:'11111111111111111111111111111111'},randomUUID(),'session-a'),/InvalidPreflight/);const id=randomUUID();service.jobs.set(id,{id,owner:'session-a',parent_run_id:randomUUID(),status:'Completed',check_request:{source:request().source}});await assert.rejects(()=>service.submitPreflight(parent.id,{...request(),check_ids:[id]},randomUUID(),'session-a'),/InvalidCheckSelection/);service.jobs.get(id).parent_run_id=parent.id;service.jobs.get(id).check_request.source='other';await assert.rejects(()=>service.submitPreflight(parent.id,{...request(),check_ids:[id]},randomUUID(),'session-a'),/InvalidCheckSelection/);assert.equal(service.queue.length,0);}finally{await rm(directory,{recursive:true,force:true});}
});
