import {test,expect} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync,spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {once} from 'node:events';
const dir=process.env.EPLYX_REPORT_DIR||'reports/milestone5-validation';
const hash=b=>createHash('sha256').update(b).digest('hex');
const spacex={symbol:'SPACEX',owner:'2wCvQzHiDHAHTvzwPeof9H3uEzq8Bzvg38DFbvZMGkuj',source:'741ZXYKzgjPZucRhPUQFK7kKAgP1ESJwimhumgGpuPHs',recipient:'123aUGPWa93jiga876U3rLdBP86JNFSoz9tSQWCAskMc'};
async function get(page,path){return (await page.request.get(new URL(path,page.url()).href)).json();}
async function fetchWallet(page,asset){
 await expect(page.locator('[name="asset"] option')).toHaveCount(9);const catalogue=await get(page,'/api/catalogue');await page.locator('[name="scope"]').selectOption('wallet');await page.locator('[name="asset"]').selectOption(catalogue.entries.find(e=>e.assertions[0].symbol===asset.symbol).mint);await page.locator('[name="public_owner"]').fill(asset.owner);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/runs')&&r.request().method()==='POST');await page.locator('#run-analysis').click();const accepted=await response;expect(accepted.status()).toBe(202);const submitted=await accepted.json();await expect(page.locator(`.wallet-output[data-run="${submitted.id}"]`)).toBeVisible({timeout:100000});await page.locator(`[name="focused_account"][value="${asset.source}"]`).check();return get(page,`/api/runs/${submitted.id}`);
}
async function check(page,parent,asset,path){
 await expect(page.locator('.local-check-form')).toBeVisible();await page.locator('.local-check-form [name="path"]').selectOption(path);
 if(path==='Transfer')await page.locator('[name="recipient"]').fill(asset.recipient);else await page.locator('[name="minimum_output_decimal"]').fill('0.0001');
 const response=page.waitForResponse(r=>r.url().endsWith(`/api/runs/${parent.id}/checks`)&&r.request().method()==='POST');await page.locator('.local-check-form button').click();const accepted=await response;expect(accepted.status()).toBe(202);let job=await accepted.json();await expect.poll(async()=>{job=await get(page,`/api/runs/${job.id}`);return job.status;},{timeout:150000}).toBe('Completed');expect(job.result.status).toBe('Proven');await expect(page.locator(`[data-check="${job.id}"]`)).toContainText('Passed in local simulation');return job;
}
async function proposal(page,parent,successor,label,{deadline=true,days=30}={}){
 await page.locator('[name="proposed_change"]').selectOption('replacement');await page.locator('[name="successor_mint"]').fill(successor);const future=new Date(Date.now()+days*86400000);const local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);await page.locator('[name="effective_at"]').fill(local(future));if(deadline)await page.locator('[name="deadline"]').fill(local(new Date(future.getTime()+30*86400000)));
 const accepted=page.waitForResponse(r=>r.url().endsWith(`/api/runs/${parent.id}/preflights`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Run pre-flight',exact:true}).click();const response=await accepted;expect(response.status()).toBe(202);let job=await response.json();await expect.poll(async()=>{job=await get(page,`/api/runs/${job.id}`);return job.status;},{timeout:180000}).toBe('Completed');await expect(page.locator(`[data-preflight="${job.id}"]`)).toBeVisible({timeout:10000});
 const bytes=await(await page.request.get(new URL(`/api/runs/${job.id}/capture`,page.url()).href)).body();const path=`${dir}/${label}.capture.json`;await writeFile(path,bytes);expect(hash(bytes)).toBe(job.capture_sha256);
 const replay=execFileSync('target/debug/eplyx-lifecycle',['replay-current-preflight','--input',path,'--run-id',parent.id,'--preflight-id',job.id,'--wallet-sha256',parent.capture_sha256,'--scenario-sha256',job.scenario_sha256,'--capture-sha256',job.capture_sha256],{env:{PATH:process.env.PATH},maxBuffer:32*1024*1024});expect(hash(replay)).toBe(job.canonical_sha256);await writeFile(`${dir}/${label}.result.json`,replay);await writeFile(`${dir}/${label}.job.json`,JSON.stringify(job,null,2));return job;
}
async function vertical(page,base,prefix,asset=spacex){
 await mkdir(dir,{recursive:true});await page.goto(`${base}/analysis#analysis`);await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});const parent=await fetchWallet(page,asset);const original=await(await page.request.get(`${base}/api/runs/${parent.id}/capture`)).body();
 const transfer=await check(page,parent,asset,'Transfer');const market=await check(page,parent,asset,'SecondaryMarketExit');
 const before=JSON.stringify([transfer.result,market.result]);const job=await proposal(page,parent,'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',`${prefix}-preflight`);const r=job.result;
 expect(r.proposed_change.source).toBe('UserProposed');expect(r.successor_verification.status).toBe('MintObserved');expect(r.views[0].lifecycle_status).toBe('Active');expect(r.views[0].readiness).toBeNull();expect(r.views[1].impact).toBe('RequiresTransition');expect(r.views[1].readiness.mobility.status).toBe('Ready');expect(r.views[1].readiness.full_transition.status).toBe('Incomplete');expect(r.paths.find(p=>p.path_type==='OfficialTransition').status).toBe('NotTested');expect(r.execution_evidence).toHaveLength(2);expect(r.population_readiness).toBeNull();expect(r.views.every(v=>v.balance_raw===r.entity.balance_raw&&v.account_sha256===r.entity.account_sha256)).toBe(true);
 expect(await(await page.request.get(`${base}/api/runs/${parent.id}/capture`)).body()).toEqual(original);expect(JSON.stringify([(await get(page,`/api/runs/${transfer.id}`)).result,(await get(page,`/api/runs/${market.id}`)).result])).toBe(before);
 const rendered=page.locator(`[data-preflight="${job.id}"]`);await expect(rendered.locator('[data-readiness="mobility"]')).toContainText('Passed');await page.getByRole('button',{name:'Technical',exact:true}).click();await expect(rendered).toContainText(job.scenario_sha256);await page.getByRole('button',{name:'Overview',exact:true}).click();await page.reload();await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});await expect(page.locator(`[data-preflight="${job.id}"] [data-readiness="full"]`)).toContainText('More evidence needed',{timeout:15000});
 await page.locator(`[data-preflight="${job.id}"]`).evaluate(e=>e.scrollIntoView({block:"start"}));await page.screenshot({path:`${dir}/${prefix}-preflight-desktop.png`});await page.setViewportSize({width:390,height:844});await page.locator(`[data-preflight="${job.id}"]`).evaluate(e=>e.scrollIntoView({block:"start"}));await page.screenshot({path:`${dir}/${prefix}-preflight-mobile.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 const refreshed=await fetchWallet(page,asset);expect(refreshed.id).not.toBe(parent.id);await expect(page.locator('.local-checks .execution-result')).toHaveCount(0);
 const missing=await proposal(page,refreshed,'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',`${prefix}-missing`);expect(missing.result.execution_evidence).toEqual([]);expect(missing.result.paths.find(p=>p.path_type==='Transfer').status).toBe('NotTested');expect(missing.result.views[1].readiness.mobility.status).toBe('Incomplete');await expect(page.locator('.previous-preflights')).toContainText('Saved previous pre-flight');
 if(prefix==='fixture'){
  const added=await check(page,refreshed,asset,'Transfer');
  await page.locator(`.preflight-form [name="evidence_check"][value="${added.id}"]`).check();
  const strengthened=await proposal(page,refreshed,'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',`${prefix}-strengthened`);
  expect(strengthened.result.views[1].readiness.mobility.status).toBe('Ready');expect(strengthened.result.proposed_change.successor_capture_sha256).toBe(missing.result.proposed_change.successor_capture_sha256);expect(strengthened.parent_capture_sha256).toBe(missing.parent_capture_sha256);
 }
 const invalid=await proposal(page,refreshed,'11111111111111111111111111111111',`${prefix}-invalid`);expect(invalid.result.preparation_status).toBe('InvalidScenario');await expect(page.locator(`[data-preflight="${invalid.id}"]`)).toContainText('Invalid proposed replacement');
 const cross=await page.request.post(`${base}/api/runs/${refreshed.id}/preflights`,{data:{request_key:crypto.randomUUID(),request:{...missing.preflight_request,check_ids:[transfer.id]}}});expect(cross.status()).toBe(400);
 await writeFile(`${dir}/${prefix}-acceptance.json`,JSON.stringify({parent,transfer,market,preflight:job,refresh:refreshed,missing,invalid},null,2));
}
test('prospective current SPACEX pre-flight reconstructed browser/service/VM',async({page})=>{
 test.setTimeout(300000);const revive=(_key,value,context)=>typeof value==='number'&&!Number.isSafeInteger(value)?JSON.rawJSON(context.source):value;
 const fixture=JSON.parse(await readFile('reports/milestone4-validation/live-market.capture.json','utf8'),revive),transfer=JSON.parse(await readFile('reports/milestone4-validation/live-transfer.capture.json','utf8'),revive);const raw=new Map();for(const c of [transfer,fixture]){const batch=c.observations.at(-1);batch.params[0].forEach((a,i)=>raw.set(a,batch.result.value[i]));}raw.set('11111111111111111111111111111111',{owner:'NativeLoader1111111111111111111111111111111',executable:true,lamports:1,space:0,data:['','base64']});
 const rpc=createServer(async(req,res)=>{let text='';for await(const b of req)text+=b;const {method,params}=JSON.parse(text);let result;if(method==='getGenesisHash')result=fixture.observations[0].result;else{let value;if(method==='getAccountInfo')value=raw.get(params[0])??null;else if(method==='getMultipleAccounts')value=params[0].map(a=>raw.get(a)??null);else if(method==='getProgramAccounts')value=fixture.observations[1].result.value;else if(method==='getTokenAccountsByOwner')value=[{pubkey:spacex.source,account:raw.get(spacex.source)}];else throw new Error(method);result={context:{slot:fixture.observations.at(-1).result.context.slot},value};}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:1,result}));});rpc.listen(0,'127.0.0.1');await once(rpc,'listening');const port=4197,base=`http://127.0.0.1:${port}`,service=spawn(process.execPath,['frontend/serve.mjs'],{env:{...process.env,PORT:String(port),SOLANA_RPC_URL:`http://127.0.0.1:${rpc.address().port}/secret`},stdio:'pipe'});
 try{await expect.poll(async()=>{try{return(await fetch(`${base}/api/health`)).status;}catch{return 0;}}).toBe(200);await vertical(page,base,'fixture');}finally{service.kill();rpc.close();await once(service,'exit');}
});
test('live prospective current SPACEX pre-flight with new checks and refresh isolation',async({page,baseURL})=>{test.skip(process.env.EPLYX_PREFLIGHT_LIVE!=='1','Opt-in bounded prospective live capture');test.setTimeout(420000);await vertical(page,baseURL,'live');});

test('live prospective OPENAI uses distinct hypothetical successor and fresh Transfer',async({page,baseURL})=>{
 test.skip(process.env.EPLYX_PREFLIGHT_LIVE!=='1','Opt-in bounded second-asset prospective capture');test.setTimeout(240000);await mkdir(dir,{recursive:true});
 const asset={symbol:'OPENAI',owner:'6GJbPKBtovsrMEEMcic5KMi5tswh9qSyT5ZYLMqEwNgt',source:'F3L4drnkirxAnqeFVpJiRgTUeNMdBFZnV4bwZKuyrSpy',recipient:'Ft3bKc8RLPz8NaXEwUdttnG1PgKiN8q3ULMX5pmQ1WeZ'};
 await page.goto(`${baseURL}/analysis#analysis`);const parent=await fetchWallet(page,asset);const transfer=await check(page,parent,asset,'Transfer');
 const job=await proposal(page,parent,'So11111111111111111111111111111111111111112','live-openai-preflight',{deadline:false,days:45});
 expect(job.result.successor_verification.status).toBe('MintObserved');expect(job.result.proposed_change.source).toBe('UserProposed');expect(job.result.views).toHaveLength(2);expect(job.result.proposed_change.lifecycle.policy.deadline).toBeNull();expect(job.result.views[1].readiness.mobility.status).toBe('Ready');expect(job.result.views[1].readiness.full_transition.status).toBe('Incomplete');
 const text=JSON.stringify(job.result);expect(text).not.toContain('PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh');expect(text).not.toContain('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v');expect(text).not.toContain('SPACEX');expect(job.result.execution_evidence.map(e=>e.check_id)).toEqual([transfer.id]);
 await writeFile(`${dir}/live-openai-acceptance.json`,JSON.stringify({parent,transfer,preflight:job},null,2));
});
