import { Header, Footer } from './shell.js';
import data from '/public/evidence/summary.js';
import { esc, number, label, badge } from './format.js';
import { readableStatus, limitations, plainPaths } from './presentation.js';
import { ledger } from './analysis.js';
const title = (n, text) => `<div class="report-section-title"><span>${n}</span><h2>${text}</h2></div>`;
const rows = values => `<dl class="scope-table">${values.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;
const matrix = paths => `<div class="path-matrix">${paths.map(p=>`<details><summary><strong>${esc(label(p.path || p.path_type))}</strong>${badge(p.status)}<span class="expand-sign" aria-hidden="true">+</span></summary><p>${esc(p.reason)}</p>${(p.attempts||[]).map(a=>rows([
 ['Exact input (raw SPACEX)',number(a.exact_input_raw)], ['Output (raw)',number(a.actual_output_raw)], ['Output mint',a.output_mint], ['Captured slot',a.clock.slot], ['Venue / context',a.context_id], ['Original owner',a.signer.authority], ['Local signer assumption','Assumed; key possession unknown'], ['Fixture SHA-256',a.fixture_sha256], ['Measurement SHA-256',a.evidence.sha256],
])).join('')}</details>`).join('')}</div>`;
const rolloutCases = () => data.rolloutCases?.length ? `<section id="rollout">${title('06','What is the proposed rollout assuming?')}<p class="report-description">Four submitted non-issuer demonstration plans assessed offline. Candidate claims, policy readiness and observed local stub behavior are separate. This viewer reads published results and does not run the guard.</p><div class="path-matrix">${data.rolloutCases.map(({assessment:a,observation:o})=>`<details data-plan="${esc(a.candidate.id)}"><summary><strong>${esc(a.candidate.label)}</strong>${badge(a.candidate_acceptance)}<span class="expand-sign" aria-hidden="true">+</span></summary>${rows([
 ['Target policy view',`${a.candidate.target_view.id} · ${a.candidate.target_view.evaluation_time}`],
 ['Policy identity',a.readiness.policy.id],['Readiness scope',a.readiness.evaluated_scope],
 ['Candidate acceptance',a.candidate_acceptance],['Policy readiness',a.readiness.overall_status],
 ['Typed readiness exit',a.readiness_exit_code],['Guarded workflow',o.disposition],
 ['Observed local marker',o.marker_created?'Created for this local demonstration only':'Not created; stub did not proceed'],
 ])}<div class="path-matrix rollout-assertions">${a.assessments.map(f=>`<details><summary><strong>${esc(a.candidate.assertions.find(c=>c.id===f.assertion_id).statement)}</strong>${badge(f.assessment)}</summary>${rows([
 ['Evidence assessment',f.assessment],['Reason codes',f.reason_codes.map(label).join('; ')],
 ['Evidence boundary',f.named_evidence_boundary],['Policy requirement IDs',f.requirement_ids.join(', ')||'No broader assurance condition is supplied by this limited policy'],
 ])}<p>${esc(f.explanation)}</p><p class="report-note">Truthful wording: ${esc(f.truthful_statement)}</p></details>`).join('')}</div><p class="report-note">Principal-removal assurance is not complete-position exit, official conversion or population rollout readiness. Historical proof does not establish current or future availability. Correcting wording or narrowing a policy does not repair or execute the position.</p></details>`).join('')}</div><p class="report-note">A refused temporary stub is a local demonstration observation. No real issuer rollout, loss prevention or mainnet intervention is claimed. Analysis exit 0 does not authorize the workflow.</p></section>` : '';
export function EvidencePage() {
 const p=data.population, pos=data.position, n=data.notice;
 const mint=n.sourceIdentity.observed_mint, usdc='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
 return `${ConsumerEvidence()}<div class="inner-page technical-only">${Header({light:true})}<main class="report-shell" id="technical-main"><div class="report-top"><div><p class="eyebrow"><span></span> Published SPACEX demonstration</p><h1>Stock transition.<br>Evidence in context.</h1><p>Published findings from frozen evidence. Viewing this report does not run a new evaluation.</p></div><div class="report-verdict is-unknown"><i></i><span>${esc(data.status)}</span><em>Population rollout readiness</em></div></div>
 <div class="evidence-context"><span>Frozen evidence</span><p>All execution proofs are conditional on exact captured state and assumed local signing. OfficialTransition remains NotTested. Readiness follows the demonstration policy and is not an asset safety judgment.</p></div>
 <div class="report-grid"><nav class="report-nav" aria-label="Evidence sections"><span>Inspect the report</span><a href="#readiness">Readiness</a><a href="#direct">Action paths</a><a href="#population">Coverage</a><a href="#notice">Notice</a><a href="#rollout">Rollout assumptions</a><a href="#artifacts">Sources</a></nav><div class="report-content">
 <section id="readiness">${title('01','The assurance findings')}<p class="report-description">Policy: <code>${esc(data.policy)}</code>. Required gaps produce Incomplete; Blocked requires an exact explicit policy violation.</p><div class="requirement-list">${data.findings.map(f=>`<article><div><h3>${esc(f.label)}</h3><small>${f.required?'Required by demo policy':'Optional historical observation'}</small></div>${badge(f.effect)}</article>`).join('')}</div></section>
 <section id="direct">${title('02','One direct holder. Five separate paths.')}<p class="report-description">The selected holder has full-input transfer and market-exit evidence in independent captured banks. Expand a path to inspect its boundary and exact measurement.</p>${rows([['Token-account entity',data.direct.entity],['Original authority',data.direct.authority],['Captured public balance',`${number(data.direct.amount)} raw SPACEX`]])}${matrix(data.direct.paths)}<p class="report-note">Unsupported describes the executor/evidence boundary. NotApplicable describes this entity context. Neither establishes that a path does not exist elsewhere.</p></section>
 <section id="position">${title('03','Principal removed. Fees and position retained.')}<p class="report-description">One decoded Meteora DLMM PositionV2, with its encoded owner retained and assumed to sign locally. Principal withdrawal does not prove a later sale or official conversion.</p>${rows([['Position',pos.entity],['Pool',pos.scope.venue],['Original authority',pos.scope.authority],['Range / fraction',`${pos.scope.range.join('…')} / ${pos.scope.bps_to_remove} bps (100%)`],['Captured finalized slot',pos.scope.captured_slot],['Fee collection',pos.fee_collection],['Position closure',pos.position_closure]])}<div class="table-scroll"><table class="quantity-table"><caption>Independent withdrawal measurement · raw token units</caption><thead><tr><th>Measurement</th><th>SPACEX</th><th>USDC</th></tr></thead><tbody>${[['Principal removed','principal_removed_raw'],['Owner credit','owner_received_raw'],['Destination withheld','destination_withheld_raw'],['Retained position fees','residual_fees_raw']].map(([text,k])=>`<tr><th>${text}</th><td>${number(pos[k][mint])}</td><td>${number(pos[k][usdc])}</td></tr>`).join('')}</tbody></table></div>${matrix(pos.paths)}</section>
 <section id="population">${title('04','Coverage does not spread to untested peers.')}<div class="metric-row">${[['Token accounts',p.token_account_entities],['Positive balances',p.positive_balance_entities],['Full-amount evidence',p.entities_with_measured_amount],['Positive evidence gaps',p.positive_balance_entities-p.entities_with_measured_amount]].map(([t,v])=>`<article><span>${t}</span><strong>${number(v)}</strong></article>`).join('')}</div><p class="report-description">The LP position is separate from this token-account population. Protocol vault exposure overlaps token accounts and is never added as more holders or capital.</p>${rows([['Represented public amount (raw)',number(p.represented_amount_raw)],['Conditional measured envelope (raw)',number(p.covered_amount_raw)],['Amount without evidence (raw)',number(p.without_evidence_raw)],['Distinct observed authorities',number(p.distinct_owner_authorities)]])}<div class="table-scroll"><table class="quantity-table"><caption>Positive entities without matching requested-path evidence</caption><thead><tr><th>Observed authority class</th><th>Entities</th></tr></thead><tbody>${Object.entries(p.account_types).map(([k,v])=>`<tr><th>${esc(label(k))}</th><td>${number(v.positive_balance_entities-v.authorities_with_measured_amount)}</td></tr>`).join('')}</tbody></table></div><p class="report-note">The amount envelope uses maxima across independent amounts, paths and venues. It is not simultaneous capacity, proceeds or valuation. Transfer evidence proves movement only.</p></section>
 <section id="notice">${title('05','Assertions, identity and assumptions stay separate.')}<p class="report-description">One captured notice from <a href="${esc(n.source)}" target="_blank" rel="noreferrer">prestocks.com/spacex ↗</a>. Its instruction permits SPCXx or any other token. Source wording does not grant official-transition proof.</p>${rows([['Issuer-stated deadline',n.deadlineWording],['Effective timestamp in notice',n.effectiveAt],['Official mechanism',n.mechanism],['Conversion ratio',n.ratio],['Official execution',n.officialStatus],['Demo policy evaluation time',data.evaluatedAt]])}<div class="provenance-cards"><article><span>IssuerAsserted</span><h3>Published notice</h3><p>The transition wording and deadline are issuer assertions. Its listing and expiry statements are not independently verified market or valuation facts.</p></article><article><span>OnChainVerified</span><h3>Captured identity</h3><p>Both published mint addresses match separately decoded Token-2022 account bytes at captured slot ${n.sourceIdentity.slot}.</p></article><article><span>DemoConfigured</span><h3>Explicit time and policy</h3><p>The hypothetical effective boundary and exclusive minute cutoff are demo choices. The assurance policy is separate from issuer policy.</p></article><article><span>Unknown</span><h3>Conversion mechanics</h3><p>No exact official conversion plan, ratio, eligibility or signing access is established. Unknown stays unknown.</p></article></div>${rows([['Source mint',n.sourceIdentity.observed_mint],['Successor mint',n.successorIdentity.observed_mint],['Captured HTML SHA-256',n.sourceDigest]])}<p class="report-note">The engine regenerates normalized source outputs before use and checks exact economic-policy compatibility. Frozen path and readiness evidence retains its original scenario hashes. This viewer only reads published artifacts.</p></section>
 ${rolloutCases()}
 <section id="artifacts">${title('07','Inspect the published source artifacts')}<p class="report-description">Build-time SHA-256 checks pin these exact report bytes. These pins are integrity checks relative to trusted artifacts, not a fresh execution attestation.</p><div class="artifact-list">${data.artifacts.map(a=>`<article><a href="${a.href}" download>${esc(a.file.split('/').at(-1))}<span>Download JSON ↓</span></a><code>${a.sha256}</code></article>`).join('')}</div><a class="text-link" href="/public/evidence/lifecycle-phase-12-production-report.md" download>Download Phase 12 production report ↗</a></section>
 <details id="reproduce" class="reproduction-details"><summary>Reproduce with the local engine</summary><p class="report-description">From this repository, run the offline notice pre-flight. The published result is Incomplete, with exit code 4. This frontend does not run the command.</p><div class="command-block"><pre><code id="replay-command">cargo run --locked -q -p eplyx-lifecycle-impact -- preflight-from-notice --workflow probes/spacex-notice-workflow.json</code></pre><button type="button" class="copy-command">Copy command</button><span class="copy-feedback" role="status"></span></div></details>
 </div></div></main>${Footer()}</div>`;
}
export function attachEvidence() {
 document.querySelector('.copy-command')?.addEventListener('click', async () => {
  const feedback = document.querySelector('.copy-feedback');
  try { await navigator.clipboard.writeText(document.querySelector('#replay-command').textContent); feedback.textContent='Copied'; }
  catch { feedback.textContent='Select and copy the command above.'; }
 });
}

function ConsumerEvidence() {
 return `<div class="inner-page consumer-only">${Header({light:true})}<main class="report-shell" id="main"><div class="report-top"><div><p class="eyebrow">Saved published result · Not newly computed</p><h1>What the saved example<br>has shown so far.</h1><p>${readableStatus(data.status)} under the broader demonstration requirements.</p></div></div><div class="evidence-context"><p>Earlier token movements and principal withdrawal passed local checks. Official conversion, full position exit and most accounts still need independent verification.</p></div><section><h2>Example token holding</h2>${plainPaths(data.direct.paths)}<p>These checks cover one saved example account. Official conversion has not been tested; sending tokens does not prove conversion.</p></section><section><h2>Liquidity was removed, but fees remain.</h2><p>The earlier principal withdrawal passed. Protocol fees and the position account remained; fee collection and closure need separate checks.</p>${ledger(data.position,data.position.scope.asset_mint)}</section><section><h2>What information is still needed?</h2><p>An identifiable official conversion procedure and its test inputs; independent fee collection and position closure; evidence for untested accounts. Correcting a statement or selecting narrower requirements does not repair a position.</p><a href="${esc(data.notice.source)}" target="_blank" rel="noreferrer">Saved issuer announcement ↗</a></section>${limitations}<a class="button button--primary" href="/#analysis" data-link>Run analysis using saved mainnet data ↗</a><p>For precise evidence details, use the existing toggle under the logo on the <a href="/" data-link>home page</a>.</p></main>${Footer()}</div>`;
}
