import { IntroAnimation } from './intro.js';
import { EplyxCoreScene } from './core-scene.js';
import { Header, Footer } from './shell.js';
import { workspaceLink } from './workspace.js';
import data from '/public/evidence/summary.js';
import { number, badge } from './format.js';
import { AnalysisSection } from './analysis.js';
import { readableStatus, limitations } from './presentation.js';
const transitionTerms = ['transition', 'IPO', 'merger', 'acquisition', 'delisting', 'stock split', 'share-class conversion', 'token expiry'];
const flow = [
  ['01', 'Separate sources', 'Keep pinned issuer notices, fresh RPC observations and operator claims in distinct evidence records.'],
  ['02', 'Read current state', 'Inspect a token or one public owner’s accounts; these bounded reads are not a complete holder or position scan.'],
  ['03', 'Model a scenario', 'Apply a proposed time to the same captured bytes without predicting future balances.'],
  ['04', 'Run scoped checks', 'The analysis service executes selected actions in its VM; each result stays tied to its exact account, amount and capture.'],
  ['05', 'Assess requirements', 'Use the published demo policy or CLI deployment gate. Neither establishes issuer authorization.'],
];
const proofs = [
  ['01', 'Current observations', 'What is visible on Solana now?', 'Fetch a mint and optional largest-account sample, or query all returned token accounts for one supplied public owner and mint. This is not a complete holder or protocol-position inventory.', 'Read-only RPC · exact scope'],
  ['02', 'Proposed lifecycle', 'What would a selected date change?', 'Compare lifecycle relevance on the same captured account state. A proposed date does not change balances, execution status or proof context.', 'User-proposed · offline replay'],
  ['03', 'VM checks', 'Which selected actions ran?', 'For one focused wallet account, the analysis service runs a Transfer, bounded supported DLMM market exit, or registered Eplyx demo conversion plan in its VM. After that conversion passes, the same plan can be tested against a frozen bounded sample. A separate LP-principal withdrawal is shown only as saved earlier evidence.', 'Fresh capture · no transaction submitted'],
  ['04', 'CLI & assurance', 'What can the operator workflow verify?', 'The eplyx CLI tests a registered package, bounded stress and counterexample searches, typed invariants and a deployment gate, and replays saved results offline. Verified release builds are available for macOS Apple Silicon, Linux x86_64 and Windows x86_64. Optional cloud sync only stores selected CLI artifacts for viewing.', 'Policy and package scoped'],
];
export function LandingPage({ analysis = false } = {}) {
 const p = data.population;
 return `${IntroAnimation()}<main id="main">
 <section class="hero">${Header()}
  <div class="hero__atmosphere" aria-hidden="true"><div class="hero__stars"></div><div class="hero__twinkle">${Array.from({length:16},(_,i)=>`<i style="left:${5+i*4.3}%;top:${12+(i*23)%67}%;--s:${1.4+(i%4)*.4}px;--t:${4+i%4}s;--d:${i*.3}s"></i>`).join('')}</div><div class="hero__mountains"></div></div><div class="hero__wash"></div>
  <div class="hero__copy reveal"><p class="eyebrow"><span></span> Tokenized stock lifecycle intelligence</p><h1>Understand the<span class="visually-hidden"> transition. </span><em class="transition-roll" aria-hidden="true"><span class="transition-roll__track">${[...transitionTerms, transitionTerms[0]].map(term => `<span class="transition-roll__term">${term}.</span>`).join('')}</span></em>Know the impact.</h1><p class="hero__lead">Inspect current token state, review the saved SPACEX evidence, and run bounded VM checks with their limits in view.</p><div class="hero__actions"><a href="/analysis#analysis" data-link class="button button--primary">Run analysis <span>↗</span></a><a href="#how" class="button button--text">How it works <span>↓</span></a>${workspaceLink('Team workspace <span>↗</span>', 'button button--text')}</div><p class="hero__workspace">The optional team workspace shows CLI runs you explicitly sync. It does not run analyses or receive browser-analysis captures.</p><p class="hero__scope">Read-only chain capture · Bounded VM checks · No on-chain transaction submitted</p></div>
  <div class="hero__visual reveal">${EplyxCoreScene()}</div><div class="scroll-cue"><span></span> ${analysis ? 'Scroll to run an analysis' : 'Scroll to review the saved example'}</div>
 </section>
 ${analysis ? AnalysisSection() : `
 <section class="system section" id="how"><div class="section-heading reveal"><p class="eyebrow eyebrow--dark"><span></span> Separate evidence paths</p><h2>Read current state.<br>Keep every result in scope.</h2><p>The saved SPACEX case, current wallet workflow and operator CLI produce different kinds of evidence.</p></div><div class="system-flow reveal technical-only">${flow.map(([n,t,b],i)=>`<article class="flow-step ${i===2?'flow-step--engine':''}"><span>${n}</span><h3>${t}</h3><p>${b}</p>${i<4?'<i>›</i>':''}</article>`).join('')}</div><div class="consumer-only system-flow reveal"><article class="flow-step"><span>01</span><h3>Choose what to inspect</h3><p>Use the saved SPACEX example, fetch a token, or query one public owner for one selected mint.</p></article><article class="flow-step"><span>02</span><h3>Read current data</h3><p>Capture mint or account state through the configured read-only Solana RPC. A token overview samples at most 20 largest accounts.</p></article><article class="flow-step"><span>03</span><h3>Model a proposed date</h3><p>For one focused wallet account, compare the same captured bytes before and after a user-proposed time. No future balance is predicted.</p></article><article class="flow-step"><span>04</span><h3>Run selected checks</h3><p>Eligible wallet accounts can run bounded Transfer, supported market-exit and candidate-conversion checks in the analysis service VM.</p></article><article class="flow-step"><span>05</span><h3>Read exact limits</h3><p>Review the account, amount, route, capture and assumptions. These checks do not establish official issuer conversion.</p></article></div></section>
 <section class="proofs section section--ink" id="product"><div class="section-heading section-heading--light reveal"><p class="eyebrow"><span></span> What Eplyx can check</p><h2>Understand the change.<br>Inspect the consequence.</h2><p>Browser workflows, pinned SPACEX findings and operator tools have separate scopes.</p></div><div class="proof-grid reveal technical-only">${proofs.map(([n,t,q,b,s])=>`<article><div><span>${n} / ${t}</span><small>${s}</small></div><h3>${q}</h3><p>${b}</p></article>`).join('')}</div><div class="consumer-only proof-grid reveal"><article><div><span>01 / Current observations</span></div><h3>What is visible now?</h3><p>Inspect a token mint or query one public owner for that mint. A largest-account sample is bounded; owner results do not include protocol positions.</p></article><article><div><span>02 / Proposed lifecycle</span></div><h3>What would a selected date change?</h3><p>Compare lifecycle relevance on the same captured account state. A proposed date does not change balances or execution evidence.</p></article><article><div><span>03 / VM simulations</span></div><h3>Which selected actions ran?</h3><p>Test a wallet-account transfer, one supported DLMM market route, or the registered Eplyx demo conversion plan. If that conversion passes, the same plan can be tested against a frozen bounded account sample. The LP-principal withdrawal shown in the saved case is earlier evidence, not a fresh browser check.</p></article><article><div><span>04 / CLI & assurance</span></div><h3>What can operators verify?</h3><p>The eplyx CLI tests packaged candidate bytes, bounded stress cases and typed invariants, supports offline replay and counterexample reproduction, and applies a deployment gate. Verified release builds cover macOS Apple Silicon, Linux x86_64 and Windows x86_64. Optional cloud sync displays selected CLI artifacts; it supplies no new proof.</p></article></div></section>
 <section class="result section" id="result"><div class="section-heading reveal"><p class="eyebrow eyebrow--dark"><span></span> The published SPACEX demonstration</p><h2>The SPACEX<br>demonstration.</h2><p>Saved published findings: more evidence is needed under the demonstration requirements. This section is a saved result, not a new analysis; open the analysis page to fetch current observations.</p></div>
 <div class="result-window reveal technical-only"><div class="window-bar"><span><i></i><i></i><i></i></span><b>eplyx / stock transition / frozen pre-flight</b><em>Published result</em></div><div class="result-summary"><div><p>SPACEX demo population readiness</p><h3 class="status-incomplete">${data.status}</h3></div><div><p>Frozen population</p><h3>${number(p.token_account_entities)}</h3><span>token-account entities</span></div><div><p>Exact mobility coverage</p><h3>${number(p.entities_with_measured_amount)}</h3><span>full represented-amount entities</span></div><a href="/evidence" data-link>Inspect evidence <span>↗</span></a></div><div class="findings"><article class="finding"><div>${badge('Satisfied')}<span>Selected holder</span></div><h3>Direct mobility</h3><p>Independent transfer and market-exit evidence</p><dl><dt>Exact input</dt><dd>${number(data.direct.amount)} raw SPACEX</dd><dt>Official transition</dt><dd>NotTested</dd></dl></article><article class="finding"><div>${badge('Satisfied')}<span>One LP position</span></div><h3>Principal withdrawal</h3><p>Native Meteora DLMM liquidity removal</p><dl><dt>Range / fraction</dt><dd>−102…−53 / 100%</dd><dt>Fees & position closure</dt><dd>NotTested</dd></dl></article></div></div><p class="demo-note technical-only">${number(p.entities_with_measured_amount)} of ${number(p.positive_balance_entities)} positive accounts have full represented-amount mobility evidence; samples do not prove peers. Results use frozen captures and assumed local signing, with key possession unknown. Readiness follows the demo policy, not an asset safety judgment.</p><div class="consumer-only saved-answer"><h3>${readableStatus(data.status)}</h3><p>Selected token movements and liquidity-principal withdrawal passed earlier local checks. Official conversion, fee collection, position closure and most accounts still need verification.</p><a href="/evidence" data-link>Explore the saved findings ↗</a>${limitations}</div></section>
 `}
 </main>${Footer()}`;
}
