import { IntroAnimation } from './intro.js';
import { EplyxCoreScene } from './core-scene.js';
import { Header, Footer } from './shell.js';
import { workspaceLink } from './workspace.js';
import data from '/public/evidence/summary.js';
import { number, badge } from './format.js';
import { AnalysisSection } from './analysis.js';
import { readableStatus, limitations } from './presentation.js';
const transitionTerms = ['transition', 'IPO', 'merger', 'acquisition', 'delisting', 'stock split', 'share-class conversion', 'token expiry'];
const flow = [
  ['01', 'Captured notice', 'Extract issuer assertions with exact source provenance.'],
  ['02', 'Frozen state', 'Bind token accounts, mint identity and protocol exposure.'],
  ['03', 'Lifecycle impact', 'Apply explicit policy to before and after time views.'],
  ['04', 'Scoped evidence', 'Inspect independently replayed paths and native withdrawal.'],
  ['05', 'Readiness decision', 'Check pinned evidence against a demonstration policy.'],
];
const proofs = [
  ['01', 'Notice & identity', 'What does the source actually say?', 'Extract a captured issuer notice and verify its published mint identities. Unknown conversion mechanics stay unknown.', 'Source scoped'],
  ['02', 'Lifecycle impact', 'Which accounts and exposures change?', 'Compare before and after policy views of frozen token accounts and verified protocol exposure.', 'Offline evaluation'],
  ['03', 'Action paths', 'Which actions have execution evidence?', 'Test selected transfers, market exits and one LP principal withdrawal locally, with exact scope and assumed signing.', 'Bounded local execution'],
  ['04', 'Assurance & coverage', 'Is the evidence enough for this policy?', 'Measure evidence coverage and evaluate Ready, Blocked or Incomplete under an explicit demo policy.', 'Policy dependent'],
];
export function LandingPage({ analysis = false } = {}) {
 const p = data.population;
 return `${IntroAnimation()}<main id="main">
 <section class="hero">${Header()}
  <div class="hero__atmosphere" aria-hidden="true"><div class="hero__stars"></div><div class="hero__twinkle">${Array.from({length:16},(_,i)=>`<i style="left:${5+i*4.3}%;top:${12+(i*23)%67}%;--s:${1.4+(i%4)*.4}px;--t:${4+i%4}s;--d:${i*.3}s"></i>`).join('')}</div><div class="hero__mountains"></div></div><div class="hero__wash"></div>
  <div class="hero__copy reveal"><p class="eyebrow"><span></span> Tokenized stock lifecycle intelligence</p><h1>Understand the<span class="visually-hidden"> transition. </span><em class="transition-roll" aria-hidden="true"><span class="transition-roll__track">${[...transitionTerms, transitionTerms[0]].map(term => `<span class="transition-roll__term">${term}.</span>`).join('')}</span></em>Know the impact.</h1><p class="hero__lead">Understand what changes for holders, which actions passed earlier local checks, and what still needs checking.</p><div class="hero__actions"><a href="/analysis#analysis" data-link class="button button--primary">Run analysis <span>↗</span></a><a href="#how" class="button button--text">How it works <span>↓</span></a>${workspaceLink('Team workspace <span>↗</span>', 'button button--text')}</div><p class="hero__workspace">Optional: open the team workspace for synced local and CI runs. Analysis always runs locally.</p><p class="hero__scope">Fresh token inspection · Saved example available · No funds moved</p></div>
  <div class="hero__visual reveal">${EplyxCoreScene()}</div><div class="scroll-cue"><span></span> Scroll to review the example</div>
 </section>
 ${analysis ? AnalysisSection() : `
 <section class="system section" id="how"><div class="section-heading reveal"><p class="eyebrow eyebrow--dark"><span></span> One traceable system</p><h2>From a lifecycle notice<br>to a measured consequence.</h2><p>Choose the saved example, compare scenario dates and review what passed and what still needs evidence.</p></div><div class="system-flow reveal technical-only">${flow.map(([n,t,b],i)=>`<article class="flow-step ${i===2?'flow-step--engine':''}"><span>${n}</span><h3>${t}</h3><p>${b}</p>${i<4?'<i>›</i>':''}</article>`).join('')}</div><div class="consumer-only system-flow reveal"><article class="flow-step"><span>01</span><h3>Read the announcement</h3><p>Understand what the issuer has stated and what remains unknown.</p></article><article class="flow-step"><span>02</span><h3>Review saved holdings</h3><p>Use observed example holdings rather than a live blockchain scan.</p></article><article class="flow-step"><span>03</span><h3>Choose a scenario</h3><p>Compare saved observations at the selected transition stage.</p></article><article class="flow-step"><span>04</span><h3>Run the checker</h3><p>Verify saved inputs and evaluate the existing requirements.</p></article><article class="flow-step"><span>05</span><h3>Understand the result</h3><p>See the exact scope, evidence gaps and next checks needed.</p></article></div></section>
 <section class="proofs section section--ink" id="product"><div class="section-heading section-heading--light reveal"><p class="eyebrow"><span></span> What Eplyx can establish</p><h2>Understand the change.<br>Inspect the consequence.</h2><p>Four capabilities, demonstrated with SpaceX PreStocks on Solana.</p></div><div class="proof-grid reveal technical-only">${proofs.map(([n,t,q,b,s])=>`<article><div><span>${n} / ${t}</span><small>${s}</small></div><h3>${q}</h3><p>${b}</p></article>`).join('')}</div><div class="consumer-only proof-grid reveal"><article><div><span>01 / Announcement</span></div><h3>What is changing?</h3><p>Read the saved issuer announcement. Identifying a replacement token does not prove conversion.</p></article><article><div><span>02 / Holdings</span></div><h3>What does the stage mean?</h3><p>See how the same saved example holdings are interpreted at each scenario date.</p></article><article><div><span>03 / Earlier checks</span></div><h3>What passed locally?</h3><p>Inspect token movement and principal withdrawal separately. Signing access was assumed, not verified.</p></article><article><div><span>04 / Requirements</span></div><h3>What still needs checking?</h3><p>Review the demonstration requirements. A narrow principal-removal result cannot establish broader rollout readiness.</p></article></div></section>
 <section class="result section" id="result"><div class="section-heading reveal"><p class="eyebrow eyebrow--dark"><span></span> The published SPACEX demonstration</p><h2>The SPACEX<br>demonstration.</h2><p>Saved published findings: more evidence is needed under the demonstration requirements. This section is a saved result, not a new analysis; open the analysis page to fetch current observations.</p></div>
 <div class="result-window reveal technical-only"><div class="window-bar"><span><i></i><i></i><i></i></span><b>eplyx / stock transition / frozen pre-flight</b><em>Published result</em></div><div class="result-summary"><div><p>Population readiness</p><h3 class="status-incomplete">${data.status}</h3></div><div><p>Frozen population</p><h3>${number(p.token_account_entities)}</h3><span>token-account entities</span></div><div><p>Exact mobility coverage</p><h3>${number(p.entities_with_measured_amount)}</h3><span>full represented-amount entities</span></div><a href="/evidence" data-link>Inspect evidence <span>↗</span></a></div><div class="findings"><article class="finding"><div>${badge('Satisfied')}<span>Selected holder</span></div><h3>Direct mobility</h3><p>Independent transfer and market-exit evidence</p><dl><dt>Exact input</dt><dd>${number(data.direct.amount)} raw SPACEX</dd><dt>Official transition</dt><dd>NotTested</dd></dl></article><article class="finding"><div>${badge('Satisfied')}<span>One LP position</span></div><h3>Principal withdrawal</h3><p>Native Meteora DLMM liquidity removal</p><dl><dt>Range / fraction</dt><dd>−102…−53 / 100%</dd><dt>Fees & position closure</dt><dd>NotTested</dd></dl></article></div></div><p class="demo-note technical-only">${number(p.entities_with_measured_amount)} of ${number(p.positive_balance_entities)} positive accounts have full represented-amount mobility evidence; samples do not prove peers. Results use frozen captures and assumed local signing, with key possession unknown. Readiness follows the demo policy, not an asset safety judgment.</p><div class="consumer-only saved-answer"><h3>${readableStatus(data.status)}</h3><p>Selected token movements and liquidity-principal withdrawal passed earlier local checks. Official conversion, fee collection, position closure and most accounts still need verification.</p><a href="/evidence" data-link>Explore the saved findings ↗</a>${limitations}</div></section>
 `}
 </main>${Footer()}`;
}
