// Build the local-dashboard presentation fixture from real `.eplyx/` stores.
//
//   node scripts/dashboard-fixture.mjs <out> <project-dir>=<name>[:run_id,...] ...
//
// Copies only the small artifacts the dashboard summarizes. Large captures and
// program bytes are omitted, and the duplicated per-case execution contexts in
// stress/failure rows are dropped (the conversion context is kept), so the
// fixture is for presentation tests only and cannot be replayed.
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const [out, ...sources] = process.argv.slice(2);
if (!out || !sources.length) {
  console.error('usage: node scripts/dashboard-fixture.mjs <out> <project-dir>=<name>[:run,...] ...');
  process.exit(2);
}
const exists = path => stat(path).then(() => true, () => false);
const RUN_FILES = ['metadata.json', 'result/report.md', 'result/bindings.json', 'result/wallet.capture.json', 'package/eplyx.json', 'package/config.json', 'search/counterexamples.json'];

await rm(out, { recursive: true, force: true });
for (const source of sources) {
  const [directory, spec] = source.split('=');
  const [name, only] = spec.split(':');
  const target = join(out, name);
  const store = join(directory, '.eplyx');
  await mkdir(join(target, '.eplyx/runs'), { recursive: true });
  await mkdir(join(target, '.eplyx/counterexamples'), { recursive: true });
  await mkdir(join(target, '.eplyx/cache'), { recursive: true });
  const project = JSON.parse(await readFile(join(store, 'project.json'), 'utf8'));
  await writeFile(join(target, '.eplyx/project.json'), `${JSON.stringify({ ...project, name }, null, 2)}\n`);
  const runs = only ? only.split(',') : (await readdir(join(store, 'runs'))).filter(id => id.startsWith('run_'));
  for (const run of runs) {
    for (const file of RUN_FILES) {
      if (!(await exists(join(store, 'runs', run, file)))) continue;
      await mkdir(join(target, '.eplyx/runs', run, file.split('/').slice(0, -1).join('/')), { recursive: true });
      await cp(join(store, 'runs', run, file), join(target, '.eplyx/runs', run, file));
    }
    const report = JSON.parse(await readFile(join(store, 'runs', run, 'result/report.json'), 'utf8'));
    for (const field of ['stress_results', 'failed_cases', 'failures']) for (const row of report[field] ?? []) delete row.execution_context;
    await writeFile(join(target, '.eplyx/runs', run, 'result/report.json'), JSON.stringify(report));
  }
  for (const file of await readdir(join(store, 'counterexamples'))) {
    const saved = JSON.parse(await readFile(join(store, 'counterexamples', file), 'utf8'));
    if (runs.includes(saved.parent_run)) await cp(join(store, 'counterexamples', file), join(target, '.eplyx/counterexamples', file));
  }
  if (await exists(join(store, 'reproductions'))) {
    await mkdir(join(target, '.eplyx/reproductions'), { recursive: true });
    for (const file of await readdir(join(store, 'reproductions'))) {
      const record = JSON.parse(await readFile(join(store, 'reproductions', file), 'utf8'));
      if (runs.includes(record.parent_run)) await cp(join(store, 'reproductions', file), join(target, '.eplyx/reproductions', file));
    }
  }
}
await writeFile(join(out, 'README.md'), `# Local dashboard presentation fixture

Generated by \`scripts/dashboard-fixture.mjs\` from real Milestone 15 local CLI
stores (healthy, underfunded and second-asset projects). Metadata, reports,
search results, saved counterexamples and reproduction records are copied unchanged except that
report.json drops duplicated per-case \`execution_context\` rows. Captures and
candidate bytes are omitted, so these runs cannot be replayed; they exist only
to test the read-only dashboard's presentation and API.
`);
console.log(`Wrote dashboard fixture to ${out}`);
